makefile: add pgo flags for ldc too
it works the same as with clang

... though i'm getting this with ldc 1.40.1:

% make ldc pgo=2
ldc2 -mcpu=native -g -fprofile-use   src/*.d src/*/*.d --of=demoreader
src/main.d(16): Error: unable to read module `dr`
src/main.d(16):        Expected 'demoreader/dr.d' or 'demoreader/dr/pack
 age.d' in one of the following import paths:
import path[0] = /opt/ldc2-1.40.1-linux-x86_64/bin/../import
make: *** [Makefile:54: ldc] Error 1

that should not affect module resolution so no idea why it's giving
this. assuming it's a bug that'll be fixed in another version.